site_name: Proyecto de Jesús Saorín
site_url: https://jsr94.github.io/proyecto-mkdocs/
theme:
  name: material

nav:
  - Inicio: index.md
  - Sobre mí: sobremi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences